### GET index
GET http://localhost/ HTTP/1.1

### GET items
GET http://localhost/api/v1/coins HTTP/1.1

### GET single item
POST http://localhost/api/v1/coin/single HTTP/1.1
Content-Type: application/json;
{
  "name": "BNB"
}
### ADD item
POST http://localhost/api/v1/coin HTTP/1.1
content-type: application/json;

{
  "name": "ETH"
}

### DELETE item
DELETE http://localhost/api/v1/coin HTTP/1.1
content-type: application/json;

{
  "name": "ETH"
}

### UPDATE item
PUT http://localhost/api/v1/coin HTTP/1.1
content-type: application/json;

{
  "name": "ETH",
  "updated_name:"BTC"
}


### GET history
GET http://localhost:5000/history HTTP/1.1
